name: Cypress Tests

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set BUILD_NAME
        id: build_name
        run: echo "BUILD_NAME=$(date '+%Y-%m-%d %H:%M:%S') | ${GITHUB_REF##*/} | ${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_NAME: ${{ env.BUILD_NAME }}
